// ===== WINDOWS 8 WEB STORE — APPS DATA =====
// appType: 'builtin'  → calls openFn on the parent OS window
// appType: 'url'      → opens appUrl in an OS iframe window

const STORE_APPS = [
  // ── PRODUCTIVITY ──
  {
    id: "calc-pro",
    name: "Calculator Pro",
    icon: "🧮",
    category: "productivity",
    color: "rgba(0,120,212,0.18)",
    rating: 4.7, reviews: 12400,
    size: "1.2 MB", version: "2.1.0", price: "Free",
    publisher: "Win8 Web Labs",
    featured: true, topFree: true,
    appType: "builtin",
    openFn: "openCalculator",   // function name in main OS
    appUrl: null,
    description: "A powerful scientific calculator built for Windows 8 Web. Supports standard, scientific, and programmer modes. Features history tracking and an elegant Metro UI design.",
    screenshots: ["🧮","📐","🔢"],
    tags: ["math","science","utility","calculator"],
  },
  {
    id: "sticky-notes",
    name: "Sticky Notes",
    icon: "📝",
    category: "productivity",
    color: "rgba(255,186,8,0.18)",
    rating: 4.5, reviews: 8900,
    size: "0.8 MB", version: "1.4.2", price: "Free",
    publisher: "Win8 Web Labs",
    featured: true, topFree: true,
    appType: "builtin", openFn: null, appUrl: null,
    description: "Quickly jot down ideas, reminders, and to-dos with colorful sticky notes pinned right on your Windows 8 Web desktop.",
    screenshots: ["📝","🗒️","✏️"],
    tags: ["notes","productivity","reminders"],
  },
  {
    id: "pdf-reader",
    name: "PDF Reader",
    icon: "📄",
    category: "productivity",
    color: "rgba(220,38,38,0.18)",
    rating: 4.3, reviews: 5600,
    size: "2.4 MB", version: "3.0.1", price: "Free",
    publisher: "DocSoft",
    featured: false, topFree: true,
    appType: "builtin", openFn: null, appUrl: null,
    description: "View PDF documents natively in Windows 8 Web with smooth scrolling, zoom, annotations, and bookmark support.",
    screenshots: ["📄","🔍","📖"],
    tags: ["pdf","reader","documents","viewer"],
  },
  {
    id: "calendar-app",
    name: "Calendar",
    icon: "📅",
    category: "productivity",
    color: "rgba(0,173,239,0.18)",
    rating: 4.6, reviews: 10200,
    size: "1.5 MB", version: "2.3.0", price: "Free",
    publisher: "Win8 Web Labs",
    featured: true, topFree: false,
    appType: "builtin", openFn: null, appUrl: null,
    description: "Stay organized with the full-featured Calendar app. Manage events, reminders, and appointments across day, week, and month views.",
    screenshots: ["📅","🗓️","⏰"],
    tags: ["calendar","schedule","events","planner"],
  },
  {
    id: "task-manager",
    name: "Task Manager",
    icon: "📊",
    category: "productivity",
    color: "rgba(22,163,74,0.18)",
    rating: 4.4, reviews: 7300,
    size: "1.1 MB", version: "1.8.0", price: "Free",
    publisher: "SystemCore",
    featured: false, topFree: false,
    appType: "builtin", openFn: null, appUrl: null,
    description: "Monitor and manage running apps and system performance right from your Windows 8 Web environment.",
    screenshots: ["📊","💻","⚡"],
    tags: ["system","monitor","performance"],
  },

  // ── ENTERTAINMENT ──
  {
    id: "music-player",
    name: "Groove Music",
    icon: "🎵",
    category: "entertainment",
    color: "rgba(126,34,206,0.18)",
    rating: 4.8, reviews: 19500,
    size: "3.2 MB", version: "4.1.0", price: "Free",
    publisher: "Win8 Web Labs",
    featured: true, topFree: true,
    appType: "builtin", openFn: null, appUrl: null,
    description: "Stream and organize your music collection with Groove Music for Windows 8 Web. Features a gorgeous visualizer and playlist management.",
    screenshots: ["🎵","🎧","🎶"],
    tags: ["music","audio","player","groove"],
  },
  {
    id: "video-player",
    name: "Movies & TV",
    icon: "🎬",
    category: "entertainment",
    color: "rgba(220,38,38,0.18)",
    rating: 4.5, reviews: 14200,
    size: "4.1 MB", version: "3.2.0", price: "Free",
    publisher: "Win8 Web Labs",
    featured: false, topFree: true,
    appType: "builtin", openFn: null, appUrl: null,
    description: "Watch movies and TV shows in beautiful quality. Supports HTML5 video playback, subtitles, and picture-in-picture mode.",
    screenshots: ["🎬","🎥","📽️"],
    tags: ["video","movies","tv","player"],
  },
  {
    id: "photo-viewer",
    name: "Photos",
    icon: "🖼️",
    category: "entertainment",
    color: "rgba(234,88,12,0.18)",
    rating: 4.6, reviews: 11000,
    size: "2.0 MB", version: "2.5.1", price: "Free",
    publisher: "Win8 Web Labs",
    featured: false, topFree: false,
    appType: "builtin", openFn: null, appUrl: null,
    description: "Browse and view your image collection with the Photos app. Features slideshow mode, basic editing tools, and full-screen gallery view.",
    screenshots: ["🖼️","📸","🎨"],
    tags: ["photos","images","gallery","viewer"],
  },

  // ── TOOLS ──
  {
    id: "color-picker",
    name: "Color Picker",
    icon: "🎨",
    category: "tools",
    color: "rgba(234,88,12,0.18)",
    rating: 4.3, reviews: 3200,
    size: "0.5 MB", version: "1.2.0", price: "Free",
    publisher: "DevTools Inc",
    featured: false, topFree: false,
    appType: "builtin", openFn: null, appUrl: null,
    description: "A handy color picker tool for designers and developers. Pick colors, generate palettes, convert between HEX, RGB, HSL formats.",
    screenshots: ["🎨","🖌️","🌈"],
    tags: ["color","design","developer","picker"],
  },
  {
    id: "clock-app",
    name: "Clock & Alarms",
    icon: "⏰",
    category: "tools",
    color: "rgba(15,118,110,0.18)",
    rating: 4.5, reviews: 6700,
    size: "0.9 MB", version: "2.0.0", price: "Free",
    publisher: "Win8 Web Labs",
    featured: false, topFree: true,
    appType: "builtin", openFn: null, appUrl: null,
    description: "A beautiful world clock, stopwatch, timer, and alarm app. Set multiple alarms and view the time across any timezone worldwide.",
    screenshots: ["⏰","⌛","🌍"],
    tags: ["clock","alarm","timer","world"],
  },

  // ── GAMES ──
  {
    id: "minesweeper",
    name: "Minesweeper",
    icon: "💣",
    category: "games",
    color: "rgba(22,163,74,0.18)",
    rating: 4.7, reviews: 22000,
    size: "1.3 MB", version: "5.0.2", price: "Free",
    publisher: "Classic Games Co",
    featured: true, topFree: true,
    appType: "builtin", openFn: null, appUrl: null,
    description: "The classic Minesweeper returns with a stunning Metro redesign. Beginner, intermediate, expert, and custom modes with a daily challenge leaderboard.",
    screenshots: ["💣","🏆","⚡"],
    tags: ["game","classic","puzzle","minesweeper"],
  },
  {
    id: "solitaire",
    name: "Solitaire",
    icon: "🃏",
    category: "games",
    color: "rgba(126,34,206,0.18)",
    rating: 4.8, reviews: 28000,
    size: "1.8 MB", version: "6.1.0", price: "Free",
    publisher: "Classic Games Co",
    featured: false, topFree: true,
    appType: "builtin", openFn: null, appUrl: null,
    description: "Classic Klondike Solitaire in a gorgeous Metro design. Smooth card animations, multiple themes, unlimited undo, and a daily challenge mode.",
    screenshots: ["🃏","♠️","🏆"],
    tags: ["game","cards","solitaire","classic"],
  },
  {
    id: "chess",
    name: "Chess Titans",
    icon: "♟️",
    category: "games",
    color: "rgba(120,53,15,0.18)",
    rating: 4.6, reviews: 9800,
    size: "2.2 MB", version: "3.4.0", price: "Free",
    publisher: "MindGames",
    featured: false, topFree: false,
    appType: "builtin", openFn: null, appUrl: null,
    description: "A beautiful chess game with 10 difficulty levels, move hints, and board analysis. Play against the computer or challenge a friend locally.",
    screenshots: ["♟️","♔","🧠"],
    tags: ["chess","game","strategy","board"],
  },

  // ── SOCIAL ──
  {
    id: "mail-app",
    name: "Mail",
    icon: "📧",
    category: "social",
    color: "rgba(0,120,212,0.18)",
    rating: 4.4, reviews: 13500,
    size: "2.8 MB", version: "4.0.0", price: "Free",
    publisher: "Win8 Web Labs",
    featured: false, topFree: true,
    appType: "builtin", openFn: null, appUrl: null,
    description: "A clean, fast email client designed for Windows 8 Web. Supports multiple accounts, conversation threads, and rich text compose.",
    screenshots: ["📧","✉️","📨"],
    tags: ["mail","email","communication","inbox"],
  },
  {
    id: "people-app",
    name: "People",
    icon: "👥",
    category: "social",
    color: "rgba(15,118,110,0.18)",
    rating: 4.2, reviews: 6400,
    size: "1.6 MB", version: "2.1.0", price: "Free",
    publisher: "Win8 Web Labs",
    featured: false, topFree: false,
    appType: "builtin", openFn: null, appUrl: null,
    description: "Manage your contacts and social connections with the People app. Aggregates contacts from multiple sources into one unified view.",
    screenshots: ["👥","👤","🤝"],
    tags: ["contacts","social","people","network"],
  },
];

const HERO_SLIDES = [
  { id: "calc-pro",    title: "Calculator Pro",  desc: "The most powerful calculator. Scientific, graphing & more. Free." },
  { id: "minesweeper", title: "Minesweeper",      desc: "The classic game reimagined for Windows 8 Web. Free forever." },
  { id: "music-player",title: "Groove Music",     desc: "Stream and organize your music with a gorgeous Metro visualizer." },
];
