// ===== WINDOWS 8 WEB STORE — APPS DATA =====

const STORE_APPS = [
  // ── PRODUCTIVITY ──
  {
    id: "calc-pro",
    name: "Calculator Pro",
    icon: "🧮",
    category: "productivity",
    color: "rgba(0,120,212,0.18)",
    rating: 4.7,
    reviews: 12400,
    size: "1.2 MB",
    version: "2.1.0",
    price: "Free",
    publisher: "Win8 Web Labs",
    featured: true,
    topFree: true,
    description: "A powerful scientific calculator built for Windows 8 Web. Supports standard, scientific, and programmer modes. Features history tracking, unit conversions, and an elegant Metro UI design that blends perfectly with your desktop.",
    screenshots: ["🧮", "📐", "🔢"],
    tags: ["math", "science", "utility", "calculator"],
    appUrl: null, // built-in
  },
  {
    id: "sticky-notes",
    name: "Sticky Notes",
    icon: "📝",
    category: "productivity",
    color: "rgba(255,186,8,0.18)",
    rating: 4.5,
    reviews: 8900,
    size: "0.8 MB",
    version: "1.4.2",
    price: "Free",
    publisher: "Win8 Web Labs",
    featured: true,
    topFree: true,
    description: "Quickly jot down ideas, reminders, and to-dos with colorful sticky notes pinned right on your Windows 8 Web desktop. Supports markdown formatting, auto-save, and multiple note colors.",
    screenshots: ["📝", "🗒️", "✏️"],
    tags: ["notes", "productivity", "reminders"],
    appUrl: null,
  },
  {
    id: "pdf-reader",
    name: "PDF Reader",
    icon: "📄",
    category: "productivity",
    color: "rgba(220,38,38,0.18)",
    rating: 4.3,
    reviews: 5600,
    size: "2.4 MB",
    version: "3.0.1",
    price: "Free",
    publisher: "DocSoft",
    featured: false,
    topFree: true,
    description: "View PDF documents natively in Windows 8 Web with smooth scrolling, zoom, annotations, and bookmark support. Supports page thumbnails and full-text search within documents.",
    screenshots: ["📄", "🔍", "📖"],
    tags: ["pdf", "reader", "documents", "viewer"],
    appUrl: null,
  },
  {
    id: "calendar-app",
    name: "Calendar",
    icon: "📅",
    category: "productivity",
    color: "rgba(0,173,239,0.18)",
    rating: 4.6,
    reviews: 10200,
    size: "1.5 MB",
    version: "2.3.0",
    price: "Free",
    publisher: "Win8 Web Labs",
    featured: true,
    topFree: false,
    description: "Stay organized with the full-featured Calendar app. Manage events, reminders, and appointments across day, week, and month views. Supports recurring events and color-coded categories.",
    screenshots: ["📅", "🗓️", "⏰"],
    tags: ["calendar", "schedule", "events", "planner"],
    appUrl: null,
  },
  {
    id: "task-manager",
    name: "Task Manager",
    icon: "📊",
    category: "productivity",
    color: "rgba(22,163,74,0.18)",
    rating: 4.4,
    reviews: 7300,
    size: "1.1 MB",
    version: "1.8.0",
    price: "Free",
    publisher: "SystemCore",
    featured: false,
    topFree: false,
    description: "Monitor and manage running apps and system performance right from your Windows 8 Web environment. View CPU, memory, and process info in a clean Metro-style interface.",
    screenshots: ["📊", "💻", "⚡"],
    tags: ["system", "monitor", "performance"],
    appUrl: null,
  },

  // ── ENTERTAINMENT ──
  {
    id: "music-player",
    name: "Groove Music",
    icon: "🎵",
    category: "entertainment",
    color: "rgba(126,34,206,0.18)",
    rating: 4.8,
    reviews: 19500,
    size: "3.2 MB",
    version: "4.1.0",
    price: "Free",
    publisher: "Win8 Web Labs",
    featured: true,
    topFree: true,
    description: "Stream and organize your music collection with Groove Music for Windows 8 Web. Features a gorgeous visualizer, playlist management, and seamless audio playback with album art display.",
    screenshots: ["🎵", "🎧", "🎶"],
    tags: ["music", "audio", "player", "groove"],
    appUrl: null,
  },
  {
    id: "video-player",
    name: "Movies & TV",
    icon: "🎬",
    category: "entertainment",
    color: "rgba(220,38,38,0.18)",
    rating: 4.5,
    reviews: 14200,
    size: "4.1 MB",
    version: "3.2.0",
    price: "Free",
    publisher: "Win8 Web Labs",
    featured: false,
    topFree: true,
    description: "Watch movies and TV shows in beautiful quality with Movies & TV. Supports HTML5 video playback, subtitles, and picture-in-picture mode. Comes with a built-in library organizer.",
    screenshots: ["🎬", "🎥", "📽️"],
    tags: ["video", "movies", "tv", "player"],
    appUrl: null,
  },
  {
    id: "photo-viewer",
    name: "Photos",
    icon: "🖼️",
    category: "entertainment",
    color: "rgba(234,88,12,0.18)",
    rating: 4.6,
    reviews: 11000,
    size: "2.0 MB",
    version: "2.5.1",
    price: "Free",
    publisher: "Win8 Web Labs",
    featured: false,
    topFree: false,
    description: "Browse and view your image collection with the Photos app. Features slideshow mode, basic editing tools (crop, rotate, filters), and a beautiful full-screen gallery view.",
    screenshots: ["🖼️", "📸", "🎨"],
    tags: ["photos", "images", "gallery", "viewer"],
    appUrl: null,
  },

  // ── TOOLS ──
  {
    id: "color-picker",
    name: "Color Picker",
    icon: "🎨",
    category: "tools",
    color: "rgba(234,88,12,0.18)",
    rating: 4.3,
    reviews: 3200,
    size: "0.5 MB",
    version: "1.2.0",
    price: "Free",
    publisher: "DevTools Inc",
    featured: false,
    topFree: false,
    description: "A handy color picker tool for designers and developers. Pick colors from the screen, generate palettes, convert between HEX, RGB, HSL formats, and save your favorite swatches.",
    screenshots: ["🎨", "🖌️", "🌈"],
    tags: ["color", "design", "developer", "picker"],
    appUrl: null,
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    icon: "📏",
    category: "tools",
    color: "rgba(0,173,239,0.18)",
    rating: 4.2,
    reviews: 2800,
    size: "0.6 MB",
    version: "1.0.4",
    price: "Free",
    publisher: "UtilApps",
    featured: false,
    topFree: false,
    description: "Convert between hundreds of units across length, mass, volume, temperature, speed, and more. Clean Metro UI with quick-access presets and history of recent conversions.",
    screenshots: ["📏", "⚖️", "🌡️"],
    tags: ["converter", "units", "utility", "math"],
    appUrl: null,
  },
  {
    id: "clock-app",
    name: "Clock & Alarms",
    icon: "⏰",
    category: "tools",
    color: "rgba(15,118,110,0.18)",
    rating: 4.5,
    reviews: 6700,
    size: "0.9 MB",
    version: "2.0.0",
    price: "Free",
    publisher: "Win8 Web Labs",
    featured: false,
    topFree: true,
    description: "A beautiful world clock, stopwatch, timer, and alarm app. Set multiple alarms, run a precision stopwatch, and view the time across any timezone worldwide.",
    screenshots: ["⏰", "⌛", "🌍"],
    tags: ["clock", "alarm", "timer", "world"],
    appUrl: null,
  },
  {
    id: "screenshot-tool",
    name: "Snipping Tool",
    icon: "✂️",
    category: "tools",
    color: "rgba(0,120,212,0.18)",
    rating: 4.4,
    reviews: 5100,
    size: "0.7 MB",
    version: "1.6.0",
    price: "Free",
    publisher: "SystemCore",
    featured: false,
    topFree: false,
    description: "Capture screenshots of your Windows 8 Web desktop with ease. Supports full screen, window, and custom region capture. Annotate captures with pen, highlighter, and text tools.",
    screenshots: ["✂️", "🖥️", "✏️"],
    tags: ["screenshot", "capture", "screen", "tool"],
    appUrl: null,
  },

  // ── GAMES ──
  {
    id: "minesweeper",
    name: "Minesweeper",
    icon: "💣",
    category: "games",
    color: "rgba(22,163,74,0.18)",
    rating: 4.7,
    reviews: 22000,
    size: "1.3 MB",
    version: "5.0.2",
    price: "Free",
    publisher: "Classic Games Co",
    featured: true,
    topFree: true,
    description: "The classic Minesweeper returns with a stunning Metro redesign. Beginner, intermediate, expert, and custom modes. Features a daily challenge leaderboard and achievement system.",
    screenshots: ["💣", "🏆", "⚡"],
    tags: ["game", "classic", "puzzle", "minesweeper"],
    appUrl: null,
  },
  {
    id: "solitaire",
    name: "Solitaire",
    icon: "🃏",
    category: "games",
    color: "rgba(126,34,206,0.18)",
    rating: 4.8,
    reviews: 28000,
    size: "1.8 MB",
    version: "6.1.0",
    price: "Free",
    publisher: "Classic Games Co",
    featured: false,
    topFree: true,
    description: "Classic Klondike Solitaire and Spider Solitaire in a gorgeous Metro design. Smooth card animations, multiple themes, unlimited undo, and a daily challenge mode.",
    screenshots: ["🃏", "♠️", "🏆"],
    tags: ["game", "cards", "solitaire", "classic"],
    appUrl: null,
  },
  {
    id: "chess",
    name: "Chess Titans",
    icon: "♟️",
    category: "games",
    color: "rgba(120,53,15,0.18)",
    rating: 4.6,
    reviews: 9800,
    size: "2.2 MB",
    version: "3.4.0",
    price: "Free",
    publisher: "MindGames",
    featured: false,
    topFree: false,
    description: "A beautiful chess game with 10 difficulty levels, move hints, and board analysis. Play against the computer or challenge a friend locally. Supports standard and Fischer-random chess.",
    screenshots: ["♟️", "♔", "🧠"],
    tags: ["chess", "game", "strategy", "board"],
    appUrl: null,
  },
  {
    id: "bubble-shooter",
    name: "Bubble Shooter",
    icon: "🫧",
    category: "games",
    color: "rgba(219,39,119,0.18)",
    rating: 4.4,
    reviews: 16000,
    size: "1.5 MB",
    version: "2.2.0",
    price: "Free",
    publisher: "ArcadeZone",
    featured: false,
    topFree: false,
    description: "Pop colorful bubbles in this addictive arcade game. 200+ levels, power-ups, and weekly tournaments. Smooth animations and satisfying sound effects make every pop count.",
    screenshots: ["🫧", "🎯", "⭐"],
    tags: ["game", "arcade", "casual", "bubbles"],
    appUrl: null,
  },

  // ── SOCIAL ──
  {
    id: "mail-app",
    name: "Mail",
    icon: "📧",
    category: "social",
    color: "rgba(0,120,212,0.18)",
    rating: 4.4,
    reviews: 13500,
    size: "2.8 MB",
    version: "4.0.0",
    price: "Free",
    publisher: "Win8 Web Labs",
    featured: false,
    topFree: true,
    description: "A clean, fast email client designed for Windows 8 Web. Supports multiple accounts, conversation threads, rich text compose, filters, and a unified inbox. Beautiful Metro design.",
    screenshots: ["📧", "✉️", "📨"],
    tags: ["mail", "email", "communication", "inbox"],
    appUrl: null,
  },
  {
    id: "people-app",
    name: "People",
    icon: "👥",
    category: "social",
    color: "rgba(15,118,110,0.18)",
    rating: 4.2,
    reviews: 6400,
    size: "1.6 MB",
    version: "2.1.0",
    price: "Free",
    publisher: "Win8 Web Labs",
    featured: false,
    topFree: false,
    description: "Manage your contacts and social connections with the People app. Aggregates contacts from multiple sources into one place, with profile photos, social feeds, and quick-call shortcuts.",
    screenshots: ["👥", "👤", "🤝"],
    tags: ["contacts", "social", "people", "network"],
    appUrl: null,
  },
];

// Hero banner rotation data
const HERO_SLIDES = [
  { id: "calc-pro", title: "Calculator Pro", desc: "The most powerful calculator app. Scientific, graphing & more." },
  { id: "groove-music", title: "Groove Music", desc: "Stream and organize your music with a gorgeous Metro visualizer." },
  { id: "minesweeper", title: "Minesweeper", desc: "The classic game, reimagined for Windows 8 Web. Free forever." },
];
